dofile (vim.g.base46_cache .. "mason")

return {
    PATH = "skip",
    ui = {
        icons = {
            package_pending = " ",
            package_installed = " ",
            package_uninstalled = " ",
        },
    },
    max_concurrent_installers = 10,
    ensure_installed = {
        "bash-language-server",
        "clang-format",
        "clangd",
        "cmake-language-server",
        "codelldb",
        "css-lsp",
        "deno",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint_d",
        "google-java-format",
        "gopls",
        "gradle-language-server",
        "html-lsp",
        "jdtls",
        "json-lsp",
        "lua-language-server",
        "marksman",
        "prettier",
        "prettierd",
        "prisma-language-server",
        "protolint",
        "pyright",
        "some-sass-language-server",
        "sql-formatter",
        "sqls",
        "tailwindcss-language-server",
        "taplo",
        "typescript-language-server",
        "vue-language-server",
        "xmlformatter",
        "yaml-language-server",
        "yamlfmt",
        "yamllint",
        "zls",
    },
}
