local tabufline = require("nvchad.tabufline")
local map = vim.keymap.set

map("n", "<Leader>tn", function()
    tabufline.move_buf(1)
end, { desc = "move tab to the right" })
map("n", "<Leader>tp", function()
    tabufline.move_buf(-1)
end, { desc = "move tab to the left" })
map("n", "<Leader>tx", function()
    tabufline.closeAllBufs(false)
end, { desc = "close all other tabs" })
map("n", "<Leader>tX", function()
    tabufline.closeAllBufs(true)
end, { desc = "close all tabs" })
map("n", "<Leader>tl", function()
    tabufline.closeBufs_at_direction("left")
end, { desc = "close all tabs to the left" })
map("n", "<Leader>tr", function()
    tabufline.closeBufs_at_direction("right")
end, { desc = "close all tabs to the right" })
