local telescope_builtin = require("telescope.builtin")
local map = vim.keymap.set

map("n", "<Leader>gb", function()
    telescope_builtin.git_branches()
end, { desc = "git branches" })
map("n", "<Leader>gc", function()
    telescope_builtin.git_commits()
end, { desc = "git commits" })
map("n", "<Leader>gf", function()
    telescope_builtin.git_files()
end, { desc = "git files" })
map("n", "<Leader>gs", function()
    telescope_builtin.git_stash()
end, { desc = "git stash" })
map("n", "gL", function()
    telescope_builtin.diagnostics()
end, { desc = "List diagnostics" })
