return {
    {
        "nvim-treesitter/nvim-treesitter",
        opts = {
            highlight = {
                enable = true,
            },
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = "<Leader>si",
                    node_incremental = "<Leader>si",
                    scope_incremental = "<Leader>ss",
                    node_decremental = "<Leader>sd",
                },
            },
            ensure_installed = {
                "ada",
                "agda",
                "angular",
                "apex",
                "arduino",
                "bash",
                "c",
                "c_sharp",
                "cmake",
                "cpp",
                "css",
                "dart",
                "dockerfile",
                "elixir",
                "elm",
                "erlang",
                "go",
                "graphql",
                "haskell",
                "html",
                "java",
                "javascript",
                "json",
                "julia",
                "kotlin",
                "lua",
                "markdown",
                "php",
                "prisma",
                "python",
                "ruby",
                "rust",
                "scala",
                "sql",
                "svelte",
                "typescript",
                "vim",
                "vimdoc",
                "vue",
                "zig",
                "yaml",
            },
        },
    },
}